audit_header: false
title: Lansing Real Estate Video Blog with Jeff Burke
description: Our mission at Jeff Burke & Associates is to be your best resource for Lansing real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Jeff Burke & Associates, your professional Lansing Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jeff Burke
  title:
  license_number:
  about_markdown: |
    I am a licensed Broker/Co-owner with Keller Williams Realty. I have been licensed for nearly twenty-four years, and have helped hundreds of families obtain the American Dream of Home Ownership. My team of professionals help to assist me in every transaction which guarantees a smooth and enjoyable experience. I specialize in Residential Real Estate, Income properties, and Commercial Real Estate. I service the Greater Lansing area: East Lansing, DeWitt, Grand Ledge, Holt, Mason, St. Johns, Haslett, Okemos, and Williamston.

    I specialize in first time and move-up buyers. Through my extensive knowledge with the mortgage product lines, I can better service my buyers which ultimately makes it a smooth and enjoyable experience. I strive to build friendships with each and everyone of my clients because I truly care about their well-being. Buying a home is one of the biggest investments someone can make ranking close to getting married or having children. I strive to make that experience as enjoyable as possible through my knowledge and expertise in the market.
  brand: Jeff Burke & Associates
  brokerage:
  market: Lansing
  address: '3490 Belle Chase Way Suite #130 Lansing, MI 48911'
  phone: 517-853-6385
  phone_type:
  phone2:
  phone2_type:
  email: Jeff@JeffBurkeAssociates.com
  url: https://jeffburkehomes.com

CTAs:
  first_CTA_text: Download the HomeScout App
  first_CTA_URL: https://homescout.app.link/Burke?share=a3f7cd2f-e8b2-4c59-b42a-ff65710ea6ef1578066685865
  second_CTA_text: Home Search
  second_CTA_URL: https://jeffburkehomes.com/mi/lansing/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "HomeScout App"
    CTA_text: "Search all the MLS listings and have automatic Home Sold Alerts sent to you as soon as homes sell in your neighborhood. Get a private account for free!"
    CTA_link_text: "Download the HomeScout App here"
    CTA_url: https://homescout.app.link/Burke?share=a3f7cd2f-e8b2-4c59-b42a-ff65710ea6ef1578066685865

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Lansing Home?"
    CTA_text2: "Search the entire MLS for your Lansing home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://jeffburkehomes.com/mi/lansing/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: http://business.facebook.com/jburkeassociates/?business_id=10153283000255325
  linkedin_url: https://www.linkedin.com/in/burkejef110/
  youtube_url: http://youtube.com/channel/UC0xnUkAZ6_vXBs9Ji7zWsAQ?view_as=subscriber
  twitter_url: http://twitter.com/Jeffburketeam
  instagram_url: https://www.instagram.com/jeffburkeandassociates/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Lansing Real Estate Podcast with Jeff Burke'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Lansing Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Jeff Burke & Associates - your professional Lansing Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Lansing, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jeff Burke'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: Lansing Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#D50F45'
  theme_color: '#818085'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
